[package]
name = "switcheroo"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gettext-rs = { version = "0.7.0", features = ["gettext-system"] }
glib = "0.18.0"
gtk = { version = "0.7.0", package = "gtk4", features = ["blueprint", "gnome_45"] }
gtk-macros = { version = "0.7.0", package = "gtk4-macros", features = ["blueprint"] }
adw = { version = "0.5.0", package = "libadwaita", features = ["v1_4"] }
log = "0.4.17"
once_cell = "1.17.1"
pretty_env_logger = "0.5.0"
itertools = "0.12.0"
tokio = { version = "1.27.0", features = ["process", "rt", "rt-multi-thread"] }
futures = "0.3.28"
ashpd = "0.6.0"
tempfile = "3.5.0"
regex = "1.8.1"
rand = "0.8.5"
shared_child = "1.0.0"
fdlimit = "0.3.0"
derivative = "2.2.0"
