name: switcheroo
base: core22
adopt-info: switcheroo
grade: stable
confinement: strict

parts:
  rustup:
    plugin: rust
    source: .
    rust-channel: "1.76"
    override-build: ""
    override-prime: ""

  libjxl:
    source: https://github.com/libjxl/libjxl.git
    source-tag: 'v0.10.2'
    plugin: cmake
    source-depth: 1
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DBUILD_TESTING=OFF
      - -DJPEGXL_ENABLE_BENCHMARK=OFF
      - -DJPEGXL_ENABLE_DOXYGEN=OFF
      - -DJPEGXL_ENABLE_EXAMPLES=OFF
      - -DJPEGXL_ENABLE_JNI=OFF
      - -DJPEGXL_ENABLE_JPEGLI_LIBJPEG=OFF
      - -DJPEGXL_ENABLE_MANPAGES=OFF
      - -DJPEGXL_ENABLE_PLUGINS=OFF
      - -DJPEGXL_ENABLE_SJPEG=ON
      - -DJPEGXL_ENABLE_SKCMS=ON
      - -DJPEGXL_ENABLE_TOOLS=OFF
      - -DJPEGXL_FORCE_SYSTEM_BROTLI=ON
      - -DJPEGXL_WARNINGS_AS_ERRORS=OFF
    prime:
      - -usr/include
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cmake
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/*.a
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/*.la
      - -usr/share

  magick:
    after: [libjxl]
    plugin: autotools
    source: https://github.com/ImageMagick/ImageMagick.git
    source-tag: '7.1.1-26'
    build-packages:
      - libjpeg-dev
      - libopenjp2-7-dev
      - libopenexr-dev
      - libheif-dev
      - liblcms2-dev
      - liblqr-1-0-dev
      - libraw-dev
      - libwmf-dev
      - libzip-dev
      - libzstd-dev
      - libraqm-dev
    build-environment:
      - LD_LIBRARY_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH
    source-depth: 1
    autotools-configure-parameters:
      - --prefix=/usr
      - --with-heic=yes
      - --with-rsvg=yes
      - --disable-docs
    prime:
      - -usr/lib/*/pkgconfig
      - -usr/lib/*/*.la
      - -usr/lib/*/*.a
      - -usr/include
    organize:
      usr/etc: usr/share

  switcheroo:
    after: [ rustup, magick ]
    plugin: meson
    source: https://gitlab.com/adhami3310/Switcheroo.git
    source-tag: 'v2.1.0'
    source-depth: 1
    build-snaps:
      - blueprint-compiler
    meson-parameters:
      - --prefix=/snap/switcheroo/current/usr
    organize:
      snap/switcheroo/current: .
    parse-info: [ usr/share/metainfo/io.gitlab.adhami3310.Converter.metainfo.xml ]

  deps:
    after: [ switcheroo ]
    plugin: nil
    stage-packages:
      - liblqr-1-0
      - libraw20
      - libopenexr25
      - libheif1
      - libjpeg62
      - libwmf-0.2-7
      - libzip4
      - libzstd1
      - libraqm0
    prime:
      - -usr/share/docs
      - -usr/share/lintian
      - -usr/share

  cleanup:
    after:
      - deps
    plugin: nil
    build-snaps:
      - core22
      - gnome-42-2204
    override-prime: |
      set -eux
      for snap in "core22" "gnome-42-2204"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "$CRAFT_PRIME/{}" \;
      done
    
slots:
  switcheroo:
    interface: dbus
    bus: session
    name: io.gitlab.adhami3310.Converter

apps:
  switcheroo:
    command: usr/bin/switcheroo
    common-id: io.gitlab.adhami3310.Converter
    desktop: usr/share/applications/io.gitlab.adhami3310.Converter.desktop
    extensions: [gnome]
    environment:
      MAGICK_CONFIGURE_PATH: $SNAP/usr/share/ImageMagick-7
      MAGICK_HOME: $SNAP/usr
